### ISSUE TITLE
Consuming test cases directly?

### ISSUE THREAD

**Issue by ivanr** [Netflix/bettertls#11]
Is there some documentation for how I might consume the test cases directly? I am working on a path building/validation library that's written in Java, which makes it not-very-feasible to test using the binary approach. However, if there were a JSON file with a list of all test cases, with their certificate chains and metadata (e.g., hostname, test/fail), that would make it quite straightforward. Thanks.

**Comment by ivanr** [comment]
Yes, absolutely. Thanks!

**Comment by JackOfMostTrades** [comment]
@ivanr Can you take a look [at the PR](https://github.com/Netflix/bettertls/pull/12) and let me know if this works for you?

**Comment by ivanr** [comment]
It's looking good. I checked out the PR branch and ran the export. Regarding the format, could you please include the test ID in the output as well. When something fails—as it inevitably will—it would be useful to be able to run get-test with the --suite and testId parameters to see what the test is about.

**Comment by JackOfMostTrades** [comment]
> could you please include the test ID in the output as well

Yup, that makes sense. Updated the PR.

**Comment by ivanr** [comment]
Sorry, I see that the IDs are not unique. How about this?

```
diff --git a/test-suites/cmd/bettertls/export_tests.go b/test-suites/cmd/bettertls/export_tests.go
index 6cf11c7..31897df 100644
--- a/test-suites/cmd/bettertls/export_tests.go
+++ b/test-suites/cmd/bettertls/export_tests.go
@@ -27,6 +27,7 @@ type suiteExport struct {
 
 type testCaseExport struct {
        Id               uint     `json:"id"`
+       Suite            string   `json:"suite"`
        Certificates     [][]byte `json:"certificates"`
        Hostname         string   `json:"hostname"`
        RequiredFeatures []string `json:"requiredFeatures"`
@@ -95,6 +96,7 @@ func exportTests(args []string) error {
                        }
                        testCaseExport := new(testCaseExport)
                        testCaseExport.Id = i
+                       testCaseExport.Suite = provider.Name()
                        certs, err := testCase.GetCertificates(rootCa, rootKey)
                        if err != nil {
                                return err
```

**Comment by JackOfMostTrades** [comment]
Sure, that works for me. Made that change and made a note in the docs.

**Comment by JackOfMostTrades** [comment]
Went ahead and merged the PR. I'm going to close the issue, but if you run into any problems or have suggestions for improvement, feel free to re-open!
