### ISSUE TITLE
test_case: Recursive call to `fmt.Sprintf`

### ISSUE THREAD

**Issue by jamie-digital** [Netflix/bettertls#13]
Hi there. There's currently a bug in [test_case.go](https://github.com/Netflix/bettertls/blob/939077295c05d36c53f1f386fc3ec55167360f3a/test-suites/test-case/test_case.go#L31) in `ExpectedResult.String()`. If any of the expected values is found, a string constant is returned, which is fine. If an unexpected value is found, the code calls `fmt.Sprintf`, but passes the value as a `ExpectedResult`. This will result in a recursive call to `ExpectedResult.String()`, ultimately resulting in a stack exhaustion.

The fix is as follows:

```
diff --git a/github.com/Netflix/bettertls/test-suites/test-case/test_case.go b/github.com/Netflix/bettertls/test-suites/test-case/test_case.go
index f8901b56..431c63c9 100644
--- a/github.com/Netflix/bettertls/test-suites/test-case/test_case.go
+++ b/github.com/Netflix/bettertls/test-suites/test-case/test_case.go
@@ -28,7 +28,7 @@ func (r ExpectedResult) String() string {
 	case EXPECTED_RESULT_SOFT_PASS:
 		return "SOFT_PASS"
 	}
-	return fmt.Sprintf("%v", r)
+	return fmt.Sprintf("%v", int(r))
 }
 func (r ExpectedResult) MarshalJSON() ([]byte, error) {
 	return json.Marshal(r.String())
```

**Comment by jamie-digital** [comment]
Sorry, I should have said, this isn't causing me direct issues. It was picked up by the linter and thus caused a build failure. I haven't encountered a `panic` in practice. I was running the tests directly, using `test_executor.ExecuteAllTestsLocal`.

**Comment by JackOfMostTrades** [comment]
> It was picked up by the linter

Gotcha. How does that get invoked? It'd probably be good for me to add to my build process. :)

**Comment by JackOfMostTrades** [comment]
Perfect, thanks for the tip!
