### ISSUE TITLE
Passing a Root CA into `bettertls export-tests`?

### ISSUE THREAD

**Issue by woodruffw** [Netflix/bettertls#22]
First of all, thanks for creating this test suite!

I'm currently poking around to see if I can embed your tests into [x509-limbo](https://github.com/trailofbits/x509-limbo), which covers non-TLS testcases as well. 

To do that, I'm currently running `bettertls export-tests` to generate the testcase JSON, and then check it into the repository via CI automation (to prevent a runtime dependency on Go in our own automation). 

At the moment, it looks like `bettertls export-tests` always recreates the Root CA, meaning lots of cascading changes whenever we re-generate the JSON. So, my feature request: would it be possible to have `bettertls export-tests` take a `-rootCA` option, similar to the `bettertls server` subcommand?

Thanks in advance! If this seems reasonable to you, I'd be happy to attempt a PR for this.

**Comment by JackOfMostTrades** [comment]
Yea, I think this would make sense. If you want to factor the code in run_server.go for loading a passed-in root CA and share that between run_server.go and export_tests.go I think that would be great.

**Comment by woodruffw** [comment]
Sounds good! I'll attempt that tomorrow.
