### ISSUE TITLE
EKU missing on all EEs in pathbuilding testcases?

### ISSUE THREAD

**Issue by woodruffw** [Netflix/bettertls#23]
I'm not sure if this is an intentional omission or not: the `pathbuilding` testcases appear to not specify `ExtKeyUsage` in their templates:

https://github.com/Netflix/bettertls/blob/7161932c248557acb417f73e7fbf1aa4e929a102/test-suites/pathbuilding/generate_certs.go#L45-L54

...which is in contrast to the `nameconstraints` suite, where the EKU is set for ordinary TLS server auth:

https://github.com/Netflix/bettertls/blob/7161932c248557acb417f73e7fbf1aa4e929a102/test-suites/nameconstraints/test_cases.go#L344-L357

CABF says that EEs *MUST* specify an EKU, so this is technically a profile violation (although admittedly a very minor one that most clients don't seem to check 🙂)

Example EE from the pathbuilding suite, missing an EKU:

```
-----BEGIN CERTIFICATE-----
MIICATCCAaagAwIBAgISAQypAtV5/dXFjMdsnkUPqQAZMAoGCCqGSM49BAMCMFUx
FjAUBgNVBAoTDWJldHRlcnRscy5jb20xDDAKBgNVBAMTA0lDQTEtMCsGA1UEBRMk
MWM2YzRiMmUtYmRhYy00MGNkLTliOGQtMmNhMTgwYjBhZGQ0MB4XDTIzMTEyOTE0
MTg1M1oXDTI0MTEzMDE0MTg1M1owVDEWMBQGA1UEChMNYmV0dGVydGxzLmNvbTEL
MAkGA1UEAxMCRUUxLTArBgNVBAUTJDgxZjVlZWYyLWI0MDgtNDRlZC04MjI3LWU1
NTdmNDc1MzI5MTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABKsOF8ZYzR/z+Fr4
EL/ZU+WtMtmGJcKAf33uoLHuuWj4DI8PcbXArEHBI4iKT8h4mhhteeu4dv52jTWq
HcWjn/mjVzBVMA4GA1UdDwEB/wQEAwIHgDAMBgNVHRMBAf8EAjAAMB8GA1UdIwQY
MBaAFALj8FpJ2xJaDMq6TK9CMgVI7bJFMBQGA1UdEQQNMAuCCWxvY2FsaG9zdDAK
BggqhkjOPQQDAgNJADBGAiEAheY/uunwAFFvXr6BWmYbmoqqLL2ULfhd9v0QSY2p
NcACIQCh91Xuc2Q01s1NZUPHzLCnXDnVhM6KPBm6k5OQFuoCAA==
-----END CERTIFICATE-----
```

Ref: [CABF](https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-v2.0.1.pdf) 7.1.2.7.6 Subscriber Certificate Extensions

**Comment by briansmith** [comment]
> although admittedly a very minor one that most clients don't seem to check 

No EKU means "all EKUs" so a client generally should accept one without an EKU. A linter, on the other hand, should reject such certificates.

**Comment by woodruffw** [comment]
> No EKU means "all EKUs" so a client generally should accept one without an EKU. A linter, on the other hand, should reject such certificates.

That makes intuitive sense to me; do you happen to have a ref/link for that? I can adjust my implementation, but I'd like to have something to cite 🙂 

For some other context, macOS 10.15+ rejects EEs without EKUs: https://support.apple.com/en-us/103769

**Comment by woodruffw** [comment]
> It is in RFC 5280.

Right, but isn't CABF defined as monotonically stricter than 5280? 5280 says that EE certs MAY have EKUs; CABF says that they MUST.

(This might be misunderstanding the intended scope of this test suite: I assumed that it was meant to exercise CABF's slightly stricter profiles, not 5280's.)

Either way: [testing shows](https://github.com/trailofbits/x509-limbo/actions/runs/7053174334?pr=119) that no clients care about missing EKUs on EEs, so I won't create an outlier here in my own implementation 🙂

**Comment by briansmith** [comment]
CABForum prescribes requirements for CAs, not relying parties.

**Comment by woodruffw** [comment]
Thanks, that clarifies things. 

Just to tie a knot around it: CABF defines "Relying Party" as "Any natural person or Legal Entity that relies on a Valid Certificate," and "Valid Certificate" as "A Certificate that passes the validation procedure specified in RFC 5280," so you're 100% right.

I'll leave this open for now, since I think this will still cause unintended false negatives on macOS.

**Comment by JackOfMostTrades** [comment]
> This might be misunderstanding the intended scope of this test suite: I assumed that it was meant to exercise CABF's slightly stricter profiles, not 5280's.

I would say that the test suite is meant to exercise the spec as written for TLS clients in general (such as the various TLS libraries baked into consumer-electronics that we build apps for) and not necessarily just browsers or clients of the web pki. Although I will admit that the primary motivation for building this in the early days was verifying the behavior of browsers.

Either way, it does seem not terribly useful for the test suite to be inducing a bunch of false negatives on macOS. Does macOS require the EKU extension to be marked critical? I wonder if a middle-ground is to just add a non-critical EKU to the EE certs in the test suite.

**Comment by woodruffw** [comment]
> Does macOS require the EKU extension to be marked critical? I wonder if a middle-ground is to just add a non-critical EKU to the EE certs in the test suite.

Doesn't look like it -- the ones in my keyring are all non-critical. So yeah, I think it'd suffice to add a non-crit EKU to each of these.
