### ISSUE TITLE
Lack of NoScript detection

### ISSUE THREAD

**Issue by robert-scheck** [Netflix/bettertls#3]
There should be some kind of NoScript detection (and alerting to the user before running the browser test), for both the domain "bettertls.com" and the IPv4 address "52.20.118.238" being used …otherwise this leads to quite strange results ;-)

**Comment by JackOfMostTrades** [comment]
Good call! I've added a noscript notice to the landing page. I don't believe the site is loading any script from the IP address (it just submits AJAX requests against it), so I think that should do the trick.
