### ISSUE TITLE
Support URI and rfc822Name SANs within the nameConstraints test

### ISSUE THREAD

**Issue by sleevi** [Netflix/bettertls#9]
An unfortunately increasingly common scenario I'm seeing while reviewing TLS validation code is code that will accept a match against "any" SAN field. That is, if given a `DNS-ID` reference identity of "`example.com`", a given TLS client will happily match that as an exact string match against a `uniformResourceIdentifier` or `rfc822Name` SAN as an exact string match.

For example, in an implementation based on OpenSSL, this would be a result of either ignoring the [`GENERAL_NAME::type`](https://github.com/openssl/openssl/blob/1c0eede9827b0962f1d752fa4ab5d436fa039da4/include/openssl/x509v3.h.in#L151) or explicitly supporting `GEN_URI` and `GEN_EMAIL` in addition to `GEN_DNS` when implementing the matching.

This is similar to the "IP address as a string within the `dNSName`", but while that permutation is covered by the existing tests, these other permutations are not.

Full testing of `rfc822Name` or `uniformResourceIdentifier` name isn't needed here; that is, URI-ID doesn't need to be supported as a reference-identity for validation (although it's nice to have, it's not something browsers or clients necessarily expose), but for those that already expose a "validate hostname" API, this could reveal when the implementation itself is doing something silly and allowing these other name types to be considered as hostnames.

For example, a certificate which is name constrained with a `permittedSubtrees` of `DNS:foo.example.com`, no URI constraints (in permitted or excluded), with no DNS SAN, but a URI SAN of `bar.example.com` (which is not a valid URI), should not be accepted, but some clients will happily do so.

**Comment by JackOfMostTrades** [comment]
@sleevi having finally completed a refactor of the bettertls code to make adding new test cases easier, I've just opened up a PR which I believe adds coverage for the test cases you suggested. The good news is that none of the implementations I have set up for testing (e.g. "openssl s_client", java, Go) failed any of the new tests. Let me know if there's any public project / revision you could point to where you would expect the new tests to fail.
